createdb -U dunder_mifflin blog

CREATE TYPE rates AS ENUM ('1','2','3','4','5')

-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT NOT NULL
  rating rates DEFAULT '1'
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url, description, rating)
values
  (),
  (),
  ();
